steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', '$LOCATION-docker.pkg.dev/$PROJECT_ID/ad-rank-decoder/app:$COMMIT_SHA', '.']
images:
- '$LOCATION-docker.pkg.dev/$PROJECT_ID/ad-rank-decoder/app:$COMMIT_SHA'
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'ad-rank-decoder', '--image', '$LOCATION-docker.pkg.dev/$PROJECT_ID/ad-rank-decoder/app:$COMMIT_SHA', '--region', '$REGION', '--platform', 'managed', '--quiet']
